on:
    workflow_dispatch:
        inputs:
          environment: 
            description: "Choose environment"
            required: true
            default: "statging"
            type: choice
            options:
              - statging
              - Devlopment
              - production
              
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Delpoy Application
        run: echo "Delpoying Application to ${{inputs.environment}}"