name: CI Test Pipeline NodeJs App

on:
  push:
    branches:
      - master
      - Test
      - "release/**"
    paths:
      - "src/**"
  pull_request:
    branches:
      - master
      - Test
      - "release/**"
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkou Code
        uses: actions/checkout@v7.0.0
      
      - name: Run tests
        run: npm test
